### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by RYOTA-EAST** [RYOTA-EAST/protospace-32904#1]
# URL
[https://protospace-32904.herokuapp.com/](url)

**Comment by mayumishibata-div** [comment]
RYOTA-EASTさん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
・プロトタイプ編集機能
正しく編集できた場合は詳細ページへ遷移するところ、トップ画面に遷移してしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by RYOTA-EAST** [comment]
修正完了しました

確認お願いします

**Comment by umi0910** [comment]
RYOTA-EASTさん、ご提出ありがとうございます‼︎

恐れ入りますが昨日お送りいただきましたURLにアクセスしますとこちらのissueに遷移されてきます。
念のためProtospaceのURLを再送いただけますでしょうか？

何卒よろしくお願いいたします。

**Comment by RYOTA-EAST** [comment]
# URL
https://protospace-32904.herokuapp.com/
すいません、よろしくお願いします。

**Comment by umi0910** [comment]
RYOTA-EASTさん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
